### ISSUE TITLE
Error when installing Neko-Rooms in Ubuntu 24.04 - Works fine in 23.10

### ISSUE THREAD

**Issue by SpiderSuave** [m1k1o/neko-rooms#127]
Using Linode VPS, running the Neko-Rooms installation script on a Ubuntu 23.10 works perfectly fine but on Ubuntu 24.04 the script spits out a long list of errors at the end of the run and Neko-Rooms will not start when going to the link.

Thank you for any help.

Here's part of the list of errors at the end of the script's run when running it on an Ubuntu 24.04 machine:

docker.io/m1k1o/neko:xfce
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
                        ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^

**Comment by m1k1o** [comment]
Wasn't tested with Ubuntu 24 so probably some dependencies changed.

**Comment by SpiderSuave** [comment]
> Wasn't tested with Ubuntu 24 so probably some dependencies changed.

Thank you. Do you figure it should be a quick and easy fix?

Thanks again.

**Comment by m1k1o** [comment]
Probably `docker-compose` changed to `docker compose`. So the install seems to be successful, try to just run `docker compose up -d` in the folder.

**Comment by SpiderSuave** [comment]
Thank so much...will try that.
