### ISSUE TITLE
Can not open the room,error can't connect 

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko-rooms#136]
I run the command 
git clone https://github.com/m1k1o/neko-rooms.git
cd neko-rooms/
docker pull m1k1o/neko:chromium
and then run 
docker-compose up
and visit the website  
http://43.154.199.232:8080/
![1730643511182](https://github.com/user-attachments/assets/eb744ba0-98e6-4c9d-834d-6be6626af92f)
and create the room
and visit the room
http://43.154.199.232:8080/room/admin/
but it show cannot connect
![1730643402399](https://github.com/user-attachments/assets/ade2cfde-1123-4b19-97c1-7d08e3cfc76b)

**Comment by m1k1o** [comment]
Did you modify the values before running?
https://github.com/m1k1o/neko-rooms/blob/ef4385d471ce9ad87d9d663c11b51d149ba8eeca/docker-compose.yml#L16-L17

**Comment by z2labplus** [comment]
![1730645086832](https://github.com/user-attachments/assets/d3b56aaa-b69c-4881-b5b4-c527d5271853)
I modify the docker-compose.yml
but when I run the command 
![1730645152588](https://github.com/user-attachments/assets/d6d4639e-39f9-4445-b42a-60000ed05fcc)
the error is 
Recreating 2aa2359371b0_neko-rooms_neko-rooms_1 ... 

ERROR: for 2aa2359371b0_neko-rooms_neko-rooms_1  'ContainerConfig'

ERROR: for neko-rooms  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[50685] Failed to execute script docker-compose
How to solve it ?

**Comment by z2labplus** [comment]
I modify the docker-compose.yml
version: "3.5"

networks:
  default:
    attachable: true
    name: "neko-rooms-net"

services:
  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    environment:
      - "TZ=Europe/Vienna"
      - "NEKO_ROOMS_MUX=true"
      - "NEKO_ROOMS_EPR=59000-59049"
      - "NEKO_ROOMS_NAT1TO1=43.154.199.232" # IP address of your server that is reachable from client
      - "NEKO_ROOMS_INSTANCE_URL=http://43.154.199.232:8080/" # external URL
      - "NEKO_ROOMS_INSTANCE_NETWORK=neko-rooms-net"
      - "NEKO_ROOMS_TRAEFIK_ENABLED=false"
      - "NEKO_ROOMS_PATH_PREFIX=/room/"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
![1730647904093](https://github.com/user-attachments/assets/9d857bd4-9383-42c2-aec9-891c6f0f336d)

and solve it
